src/KostenBatenTool/Controllers/AnalyseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using KostenBatenTool.Models.AnalyseViewModels;
using KostenBatenTool.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using KostenBatenTool.Models;
using KostenBatenTool.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using MimeKit;
using Microsoft.Net.Http.Headers;

namespace KostenBatenTool.Controllers
{
    public class AnalyseController : Controller
    {

        private readonly IArbeidsBemiddelaarRepository _arbeidsBemiddelaarRepository;
        private readonly IDoelgroepRepository _doelgroepRepository;
        private readonly IAnalyseRepository _analyseRepository;
        private readonly IOrganisatieRepository _organisatieRepository;
        private readonly ILijnRepository _lijnRepository;
        private readonly IBerekeningRepository _berekeningRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailService _emailService;
        private readonly IHostingEnvironment _hostingEnv;

        public AnalyseController(IHostingEnvironment hostingEnv, IDoelgroepRepository doelgroepRepository,
            IAnalyseRepository analyserepository, 
            IOrganisatieRepository organisatieRepository,
            IBerekeningRepository berekeningRepository,
            IArbeidsBemiddelaarRepository arbeidsBemiddelaarRepository,
            ILijnRepository lijnRepository,
            UserManager<ApplicationUser> userManager, IEmailService emailService)

        {
            _arbeidsBemiddelaarRepository = arbeidsBemiddelaarRepository;
            _doelgroepRepository = doelgroepRepository;
            _analyseRepository = analyserepository;
            _berekeningRepository = berekeningRepository;
            _organisatieRepository = organisatieRepository;
            _lijnRepository = lijnRepository;
            _userManager = userManager;
            _emailService = emailService;
            _hostingEnv = hostingEnv;
        }

        // GET: /<controller>/
        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, string zoekCriteria = "Werkgever")
        {
            ViewData["NameSortParm"] = sortOrder == "Naam" ? "naam_desc" : "Naam";
            ViewData["DateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewData["GemeenteSort"] = sortOrder == "Gemeente" ? "gemeente_desc" : "Gemeente";
            ViewData["AfdelingSort"] = sortOrder == "Afdeling" ? "afdeling_desc" : "Afdeling";
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentSort"] = sortOrder;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            IEnumerable<Analyse> a = _arbeidsBemiddelaarRepository.GetAllAnalysesVanArbeidsBemiddelaar(User.Identity.Name);
            if (!String.IsNullOrEmpty(searchString))
            {
                if (zoekCriteria == null || zoekCriteria.Equals("Werkgever"))
                {
                    a = _arbeidsBemiddelaarRepository.ZoekAnalysesWerkgever(User.Identity.Name, searchString);
                }
                else
                {
                    a = _arbeidsBemiddelaarRepository.ZoekAnalysesGemeente(User.Identity.Name, searchString);
                }
            }
            switch (sortOrder)
            {
                case "naam_desc":
                    a = a.OrderByDescending(s => s.Organisatie.Naam);
                    ViewData["pijlNaam"] = "fa-chevron-down";
                    break;
                case "Naam":
                    a = a.OrderBy(s => s.Organisatie.Naam);
                    ViewData["pijlNaam"] = "fa-chevron-up";
                    break;
                case "date_desc":
                    a = a.OrderByDescending(s => s.AanmaakDatum);
                    ViewData["pijlDatum"] = "fa-chevron-down";
                    break;
                case "Gemeente":
                    a = a.OrderBy(s => s.Organisatie.Gemeente);
                    ViewData["pijlGemeente"] = "fa-chevron-up";
                    break;
                case "gemeente_desc":
                    a = a.OrderByDescending(s => s.Organisatie.Gemeente);
                    ViewData["pijlGemeente"] = "fa-chevron-down";
                    break;
                case "Afdeling":
                    a = a.OrderBy(s => s.Organisatie.Afdeling);
                    ViewData["pijlAfdeling"] = "fa-chevron-up";
                    break;
                case "afdeling_desc":
                    a = a.OrderByDescending(s => s.Organisatie.Afdeling);
                    ViewData["pijlAfdeling"] = "fa-chevron-down";
                    break;
                default:
                    a = a?.OrderBy(s => s.AanmaakDatum);
                    ViewData["pijlDatum"] = "fa-chevron-up";
                    break;
            }
            int pageSize = 10;
            return View(a == null ? null : PaginatedList<Analyse>.CreateAsync(a.AsQueryable(), page ?? 1, pageSize));
        }

        public IActionResult Nieuw()
        {
            IEnumerable<Organisatie> organisaties = _arbeidsBemiddelaarRepository.GetOrganisatiesVanArbeidsBemiddelaar(User.Identity.Name);
            return View(organisaties);


        }

        public IActionResult PartialWerkgevers()
        {
            var user = GetCurrentUserAsync();
            string email = user.Result.Email;
            IEnumerable<Organisatie> organisaties = _arbeidsBemiddelaarRepository.GetOrganisatiesVanArbeidsBemiddelaar(User.Identity.Name);
            return PartialView("_werkgeversPartial", organisaties);
        }

        public IActionResult Werkgever(int id = -1, bool nieuw = false, int analyseId = -1)
        {
            ViewData["nieuw"] = nieuw;
            Organisatie o = _organisatieRepository.GetOrganisatie(id);
            WerkgeverViewModel model = o == null ? new WerkgeverViewModel() : (analyseId < 0 ? new WerkgeverViewModel(o) : new WerkgeverViewModel(o, analyseId));

            return View(model);
        }

        [HttpPost]
        public IActionResult Werkgever(WerkgeverViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                try
                {
                    Organisatie o = new Organisatie(model.Naam, model.Straat, model.Huisnummer, model.Postcode,
                        model.Gemeente);
                    o.UrenWerkWeek = Convert.ToDecimal(model.Werkuren);
                    o.PatronaleBijdrage = Convert.ToDecimal(model.Bijdrage) / 100;
                    o.Afdeling = model.Afdeling;
                    if (model.EmailContactpersoon != null)
                    {
                        Contactpersoon contactpersoon = new Contactpersoon(model.NaamContactpersoon,
                            model.VoornaamContactpersoon, model.EmailContactpersoon);
                        o.Contactpersoon = contactpersoon;
                    }
                    var user = GetCurrentUserAsync();
                    string email = user.Result.Email;
                    ArbeidsBemiddelaar a = _arbeidsBemiddelaarRepository.GetArbeidsBemiddelaarMetAnalyses(email);
                    Analyse analyse = new Analyse(o);
                    a.VoegNieuweAnalyseToe(analyse);
                    _analyseRepository.SerialiseerVelden(analyse);
                    _analyseRepository.SaveChanges();
                    return RedirectToAction(nameof(Overzicht), new { analyseId = model.AnalyseId });

                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }

            }

            ModelState.AddModelError("EmailReg", "Uw e-mailadres is onjuist, bent u al geregistreerd?");
            return View(model);
        }

        [HttpPost]
        public IActionResult WerkgeverEdit(WerkgeverViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            if (ModelState.IsValid)
            {
                try
                {
                    Organisatie o = _organisatieRepository.GetOrganisatie(model.OrganisatieId);
                    o.Naam = model.Naam;
                    o.Afdeling = model.Afdeling;
                    o.Gemeente = model.Gemeente;
                    o.Straat = model.Straat;
                    o.Huisnummer = model.Huisnummer;
                    o.UrenWerkWeek = Convert.ToDecimal(model.Werkuren);
                    o.PatronaleBijdrage = Convert.ToDecimal(model.Bijdrage) / 100;
                    if (o.Contactpersoon == null && model.EmailContactpersoon != null)
                    {
                        Contactpersoon contactpersoon = new Contactpersoon(model.NaamContactpersoon,
                            model.VoornaamContactpersoon, model.EmailContactpersoon);
                        o.Contactpersoon = contactpersoon;
                    }
                    else if (o.Contactpersoon != null)
                    {
                        o.Contactpersoon.Email = model.EmailContactpersoon;
                        o.Contactpersoon.Naam = model.NaamContactpersoon;
                        o.Contactpersoon.Voornaam = model.VoornaamContactpersoon;
                    }

                    _arbeidsBemiddelaarRepository.SaveChanges();
                    return RedirectToAction(nameof(Overzicht), new { analyseId = model.AnalyseId });
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }

            }
            ViewData["nieuw"] = false;
            return View(nameof(Werkgever), model);
        }

src/KostenBatenTool/Views/Shared/CustomLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html class="begin" lang="nl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    @*<div class="row">*@
<div class="wrapper animated fadeInDown">
    <img src="~/images/kairos_white.png" id="logoIntro1" class="img-responsive noMobile"/>
    @RenderBody()
    <div class="panel-group col-md-5 box box-right mobile" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel-group" id="accordion">
            <div class="">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            <img src="~/images/kairosLogoZwart.png" id="logoIntro"/>
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse ">
                    <div class="panel-body">
                        <p id="intro">
                            Waarom zou een werkgever investeren in het tewerkstellen van personen met een grote afstand tot de arbeidsmarkt en/of functiecreatie? We zijn geneigd te denken dat we - ook managers en bedrijfsleiders - erg rationele wezens zijn, die (grote) beslissingen weloverwogen maken. Maar... zijn menselijke beslissingen wel zo rationeel als we denken?

                            Niet echt. Mensen beslissen op basis van eigen kennis, ervaring, inschattingsvermogen en intuïtie. We gaan er vanuit dat we daarmee in staat zijn om consistente en evenwichtige beslissingen te nemen of, anders gezegd, een rationele afweging te maken. De waarheid is echter heel anders. Veel van onze besluitvorming wordt door een automatische piloot-functie van onze hersenen gedaan. Met als gevolg dat wij, en ook werkgevers, veel beslissingen nemen op basis van vooroordelen in plaats van alle beschikbare informatie in overweging te nemen.

                            Het maken van een business case kan helpen om de besluitvorming te verbeteren, want het geeft betrouwbare, op feiten gebaseerde informatie en vermindert de subjectiviteit in beoordeling en besluitvorming. De kans dat de werkgever op jouw aanbod zal ingaan, vergroot naarmate je deze vraag duidelijk en zakelijk onderbouwd weet te beantwoorden.

                            Met dit model kan je werkgevers inzicht geven in de economische waarde van het werken met mensen met een grote afstand tot de arbeidsmarkt.
                        </p>
                    </div>
                </div>
                @*</div>*@
            </div>
        </div>
    </div>
</div>
    @RenderSection("scripts", required: false)

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://use.fontawesome.com/f9fbd9e00a.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="https://use.fontawesome.com/f9fbd9e00a.js"></script>
    </environment>
</body>
</html>

src/KostenBatenTool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="dash" lang="nl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KostenBatenTool</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>

<body>
    <div class="wrap ">

        <nav class="nav-bar no-print" role="navigation">
            <div id="top-menu" class="container-fluid">
                <a class="navbar-brand col-xs-3" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/kairos_whiteKlein.png" alt="logo" id="logo" /></a>
                <div class="navbar-collapse col-xs-offset-9">
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
        <aside id="side-menu" class="aside mobile no-print" role="navigation" data-navigation='true'>
            <ul class="nav nav-list accordion">
                <li class="nav-header "><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home fa-3x" tool-tip-toggle="tooltip" data-placement="right" data-original-title="Home"></i></a></li>
                <li class="nav-header "><a asp-area="" asp-controller="Analyse" asp-action="Nieuw"><i class="fa fa-balance-scale fa-2x" tool-tip-toggle="tooltip" data-placement="right" data-original-title="Nieuwe analyse"></i></a></li>
                <li class="nav-header "><a asp-area="" asp-controller="Analyse" asp-action="Index"><i class="fa fa-archive fa-2x" tool-tip-toggle="tooltip" data-placement="right" data-original-title="Archief"></i></a></li>
            </ul>
        </aside>

        <div>
            <div class="container body-content">
                <br/>
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success">@TempData["message"]</div>
                }
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-warning">@TempData["error"]</div>
                }
                @RenderBody()

            </div>
        </div>
    </div>
   
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://use.fontawesome.com/f9fbd9e00a.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBxyKtliOFsiE46psfqY-Z6Tf0ZWAEqlkc&libraries=places&callback=initAutocomplete" async defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.0/jspdf.plugin.autotable.js"></script>
        <script src="~/js/bootbox.min.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>

        <script src="https://use.fontawesome.com/f9fbd9e00a.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBxyKtliOFsiE46psfqY-Z6Tf0ZWAEqlkc&libraries=places&callback=initAutocomplete" async defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.0/jspdf.plugin.autotable.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>